# Nginx installation and configuration
---
- name: Install Nginx
  package:
    name: nginx
    state: present
  tags: [nginx, packages]

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  tags: [nginx, service]

- name: Remove default Nginx site
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /var/www/html/index.nginx-debian.html
  notify: reload nginx
  tags: [nginx, cleanup]

- name: Create Nginx directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/nginx/conf.d
    - /var/log/nginx
  tags: [nginx, directories]

- name: Configure main Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
    mode: '0644'
  notify: reload nginx
  tags: [nginx, configuration]

- name: Configure application virtual host
  template:
    src: app-vhost.conf.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    mode: '0644'
  notify: reload nginx
  tags: [nginx, vhost]

- name: Enable application site
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link
  notify: reload nginx
  tags: [nginx, vhost]

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test_result
  changed_when: false
  failed_when: nginx_test_result.rc != 0
  tags: [nginx, verification]

- name: Create custom error pages directory
  file:
    path: /var/www/errors
    state: directory
    mode: '0755'
  tags: [nginx, errors]

- name: Configure log rotation for Nginx
  template:
    src: nginx-logrotate.j2
    dest: /etc/logrotate.d/nginx
    mode: '0644'
  tags: [nginx, logging]