name: Deploy Go API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production  # Add this line to use environment secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        # Debug: Check if secrets exist (without printing actual values)
        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "ERROR: SSH_PRIVATE_KEY secret is empty!"
          exit 1
        fi
        if [ -z "${{ secrets.HOST }}" ]; then
          echo "ERROR: HOST secret is empty!"
          exit 1
        fi
        if [ -z "${{ secrets.USER }}" ]; then
          echo "ERROR: USER secret is empty!"
          exit 1
        fi
        # Setup SSH key
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Create inventory file
      run: |
        echo "[servers]" > inventory.ini
        echo "${{ secrets.HOST }} ansible_user=${{ secrets.USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
        echo "" >> inventory.ini
        echo "[all:vars]" >> inventory.ini
        echo "ansible_python_interpreter=/usr/bin/python3" >> inventory.ini

    - name: Create Nginx template directory
      run: mkdir -p templates

    - name: Copy Nginx template
      run: cp nginx.conf.j2 templates/

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i inventory.ini deploy.yml -v

    - name: Test deployment
      run: |
        sleep 30
        curl -f http://${{ secrets.HOST }}/users || exit 1