name: Deploy Go API with Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test Go application
      run: |
        cd $GITHUB_WORKSPACE
        go mod init users-api
        go mod tidy
        go test -v ./...
        go build -v ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        # Debug: Check if secrets exist (without printing actual values)
        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "ERROR: SSH_PRIVATE_KEY secret is empty!"
          exit 1
        fi
        if [ -z "${{ secrets.ANSIBLE_HOST }}" ]; then
          echo "ERROR: ANSIBLE_HOST secret is empty!"
          exit 1
        fi
        if [ -z "${{ secrets.ANSIBLE_USER }}" ]; then
          echo "ERROR: ANSIBLE_USER secret is empty!"
          exit 1
        fi
        
        # Setup SSH key with proper name expected by Ansible config
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Add host to known_hosts
        ssh-keyscan -H ${{ secrets.ANSIBLE_HOST }} >> ~/.ssh/known_hosts

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible python3-pip
        pip3 install docker

    - name: Update Ansible inventory with current host
      run: |
        # Update the production inventory with current host from secrets
        cd ansible
        sed -i "s/userapi ansible_host=.*/userapi ansible_host=${{ secrets.ANSIBLE_HOST }} ansible_user=${{ secrets.ANSIBLE_USER }}/" inventories/production/hosts

    - name: Test SSH connection
      run: |
        echo "Testing SSH connection..."
        cd ansible
        ansible webservers -m ping -v

    - name: Copy application files to Ansible role
      run: |
        # Copy source files that the golang-app role expects
        cp main.go ansible/roles/golang-app/files/
        cp Dockerfile ansible/roles/golang-app/files/
        cp go.mod ansible/roles/golang-app/files/ 2>/dev/null || echo "go.mod not found, will be created during build"

    - name: Run infrastructure setup
      run: |
        cd ansible
        ansible-playbook playbooks/setup-infrastructure.yml -v

    - name: Deploy application
      run: |
        cd ansible
        ansible-playbook playbooks/deploy-app.yml -v

    - name: Test deployment
      run: |
        sleep 30
        echo "Testing API endpoints..."
        curl -f http://${{ secrets.ANSIBLE_HOST }}/health
        curl -f http://${{ secrets.ANSIBLE_HOST }}/users
        echo "Deployment successful!"